INSERT INTO USERCREDENTIALS (USERNAME, PASSWORD, email) VALUES ('test', 'test', 'test@t32.pl')
INSERT INTO USERGROUP (GROUPNAME, USERCREDENTIALS_ID) VALUES ('ADMIN', 1)
INSERT INTO USERCREDENTIALS (USERNAME, PASSWORD, email) VALUES ('kamil', 'kamil', 'kamil@t32.pl')
INSERT INTO USERGROUP (GROUPNAME, USERCREDENTIALS_ID) VALUES ('USER', 1)
insert into DVD (director, title, description) values ('Ridley Scott', 'Gladiator', 'Movie about Gladiator')
insert into DVD (director, title, description) values ('Brian de Palma', 'Mission Impossible', 'some wonderful description')
